[tox]
envlist =
    py{310,311}-dj{42,52}
    py{312,313}-dj{42,52,60}

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = settings.with_sqlite3
deps =
    dj42: Django>=4.2,<5.0
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    django-cte>=3.0
    factory-boy>=3.3
    pyhamcrest>=2.0
    RestrictedPython>=6.0
commands =
    python manage.py test river
