# Generated by Django 5.2.16 on 2026-07-15 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('xii_django_river', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('object_id', models.CharField(max_length=200, verbose_name='Related Object')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('JUMPED', 'Jumped')], max_length=20, verbose_name='Action')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='Actor (snapshot)')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xii_django_river.state', verbose_name='Destination State')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xii_django_river.state', verbose_name='Source State')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='xii_django_river.transition', verbose_name='Transition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='xii_django_river.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Transition Audit Log',
                'verbose_name_plural': 'Transition Audit Logs',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='xii_django__content_24354b_idx')],
            },
        ),
    ]
