# Generated by Django 5.2.16 on 2026-07-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xii_django_river', '0002_transitionauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapproval',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_approvals', to='xii_django_river.transition', verbose_name='Transition'),
        ),
    ]
