# Generated by Django 5.2.16 on 2026-07-11 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('xii_django_river', '0002_alter_onapprovedhook_callback_function_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='object_id',
            field=models.CharField(max_length=200, verbose_name='Related Object'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='object_id',
            field=models.CharField(max_length=200, verbose_name='Related Object'),
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['content_type', 'object_id'], name='river_transition_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='transitionapproval',
            index=models.Index(fields=['content_type', 'object_id'], name='river_ta_ct_obj_idx'),
        ),
    ]
