# Generated by Django 5.2.16 on 2026-07-11 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xii_django_river', '0003_unify_object_id_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'permissions': [('approve_function', 'Can approve river functions for execution')]},
        ),
        migrations.AddField(
            model_name='function',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='function',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='function',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='function',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='function',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.CreateModel(
            name='FunctionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated')], max_length=20, verbose_name='Action')),
                ('body', models.TextField(max_length=100000, verbose_name='Body Snapshot')),
                ('diff', models.TextField(blank=True, verbose_name='Diff vs Previous Version')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='xii_django_river.function', verbose_name='Function')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
