# Generated by Django 5.2.16 on 2026-07-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xii_django_river', '0003_alter_transitionapproval_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionrevision',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('APPROVED', 'Approved'), ('SELF_APPROVED', 'Self-approved'), ('AUTO_APPROVED', 'Auto-approved (create_function)')], max_length=20, verbose_name='Action'),
        ),
    ]
