# Generated by Django 5.2.16 on 2026-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0004_alter_function_options_function_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'permissions': [('approve_function', 'Can approve river functions for execution'), ('self_approve_function', 'Can approve river functions authored by oneself')]},
        ),
        migrations.AlterField(
            model_name='functionrevision',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('APPROVED', 'Approved'), ('SELF_APPROVED', 'Self-approved')], max_length=20, verbose_name='Action'),
        ),
    ]
