# Generated by Django 5.2.16 on 2026-07-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0005_alter_function_options_alter_functionrevision_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionrevision',
            name='changed_by_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Changed By (snapshot)'),
        ),
    ]
